deps = {1: "Guatemala", 2: "Sacatepéquez", 3: "Chimaltenango", 4: "El Progreso*", 5: "Escuintla", 6: "Santa Rosa*", 7: "Sololá*", 8: "Totonicapán", 9: "Quetzaltenango", 10: "Suchitepéquez*", 11: "Retalhuleu", 12: "San Marcos*", 13: "Huehuetenango", 14: "Quiché*", 15: "Baja Verapaz", 16: "Alta Verapaz", 17: "Petén", 18: "Izabal", 19: "Zacapa", 20: "Chiquimula", 21: "Jalapa", 22: "Jutiapa*"}
munis = {"0":{"0":"Nivel Nacional"},"1":{"0":"Nivel Departamental","1":"Distrito Central","2":"Santa Catarina Pinula","3":"San José Pinula","4":"San José Del Golfo","5":"Palencia","6":"Chinautla","7":"San Pedro Ayampuc","8":"Mixco","9":"San Pedro Sacatepéquez","10":"San Juan Sacatepéquez","11":"San Raimundo","12":"Chuarrancho","13":"Fraijanes","14":"Amatitlán","15":"Villa Nueva","16":"Villa Canales","17":"Petapa"},"2":{"0":"Nivel Departamental","1":"Antigua Guatemala","2":"Jocotenango","3":"Pastores","4":"Sumpango","5":"Santo Domingo Xenacoj","6":"Santiago Sacatepéquez","7":"San Bartolomé Milpas Altas","8":"San Lucas Sacatepéquez","9":"Santa Lucía Milpas Altas","10":"Magdalena Milpas Altas","11":"Santa María de Jesús","12":"Ciudad Vieja","13":"San Miguel Dueñas","14":"Alotenango","15":"San Antonio Aguas Calientes","16":"Santa Catarina Barahona"},"3":{"0":"Nivel Departamental","1":"Chimaltenango","2":"San José Poaquil","3":"San Martín Jilotepeque","4":"Comalapa","5":"Santa Apolonia","6":"Tecpán Guatemala","7":"Patzún","8":"Pochuta","9":"Patzicía","10":"Santa Cruz Balanyá","11":"Acatenango","12":"Yepocapa","13":"San Andrés Itzapa","14":"Parramos","15":"Zaragoza","16":"El Tejar"},"4":{"0":"Nivel Departamental","1":"Guastatoya","2":"Morazán*","3":"San Agustín Acasaguastlán","4":"San Cristóbal Acasaguastlán","5":"El Jícaro","6":"Sansare","7":"Sanarate","8":"San Antonio La Paz"},"5":{"0":"Nivel Departamental","1":"Escuintla","2":"Santa Lucía Cotzumalguapa","3":"La Democracia","4":"Siquinalá","5":"Masagua","6":"Tiquisate","7":"La Gomera","8":"Guanagazapa","9":"San José","10":"Iztapa","11":"Palin","12":"San Vicente Pacaya","13":"Nueva Concepción"},"6":{"0":"Nivel Departamental","1":"Cuilapa","2":"Barberena","3":"Santa Rosa De Lima","4":"Casillas","5":"San Rafael Las Flores","6":"Oratorio","7":"San Juan Tecuaco","8":"Chiquimulilla","9":"Taxisco","10":"Santa María Ixhuatán","11":"Guazacapán","12":"Santa Cruz Naranjo","13":"Pueblo Nuevo Viñas*","14":"Nueva Santa Rosa"},"7":{"0":"Nivel Departamental","1":"Sololá","2":"San José Chacayá","3":"Santa María Visitación","4":"Santa Lucía Utatlán","5":"Nahualá","6":"Santa Catarina Ixtahuacán","7":"Santa Clara La Laguna*","8":"Concepción","9":"San Andrés Semetabaj","10":"Panajachel","11":"Santa Catarina Palopó*","12":"San Antonio Palopó","13":"San Lucas Tolimán","14":"Santa Cruz La Laguna","15":"San Pablo La Laguna","16":"San Marcos La Laguna","17":"San Juan La Laguna","18":"San Pedro La Laguna","19":"Santiago Atitlán"},"8":{"0":"Nivel Departamental","1":"Totonicapán","2":"San Cristóbal Totonicapán","3":"San Francisco El Alto","4":"San Andrés Xecul","5":"Momostenango","6":"Santa María Chiquimula","7":"Santa Lucía La Reforma","8":"San Bartolo"},"9":{"0":"Nivel Departamental","1":"Quetzaltenango","2":"Salcajá","3":"Olintepeque","4":"San Carlos Sija","5":"Sibilia","6":"Cabricán","7":"Cajolá","8":"San Miguel Sigüilá","9":"Ostuncalco","10":"San Mateo",
    "11":"Concepción Chiquirichapa","12":"San Martín Sacatepéquez","13":"Almolonga","14":"Cantel","15":"Huitán","16":"Zunil","17":"Colomba","18":"San Francisco La Unión","19":"El Palmar","20":"Coatepeque","21":"Génova","22":"Flores Costa Cuca","23":"La Esperanza","24":"Palestina De Los Altos"},"10":{"0":"Nivel Departamental","1":"Mazatenango","2":"Cuyotenango","3":"San Francisco Zapotitlán*","4":"San Bernardino","5":"San José El Ídolo*","6":"Santo Domingo Suchitepéquez","7":"San Lorenzo","8":"Samayac","9":"San Pablo Jocopilas","10":"San Antonio Suchitepéquez*","11":"San Miguel Panán","12":"San Gabriel","13":"Chicacao","14":"Patulul","15":"Santa Bárbara","16":"San Juan Bautista","17":"Santo Tomás La Unión","18":"Zunilito","19":"Pueblo Nuevo","20":"Río Bravo","21":"San José La Máquina"},"11":{"0":"Nivel Departamental","1":"Retalhuleu","2":"San Sebastián","3":"Santa Cruz Muluá","4":"San Martín Zapotitlán","5":"San Felipe","6":"San Andrés Villa Seca","7":"Champerico","8":"Nuevo San Carlos","9":"El Asintal"},"12":{"0":"Nivel Departamental","1":"San Marcos","2":"San Pedro Sacatepéquez","3":"San Antonio Sacatepéquez","4":"Comitancillo","5":"San Miguel Ixtahuacán","6":"Concepción Tutuapa","7":"Tacaná","8":"Sibinal","9":"Tajumulco","10":"Tejutla","11":"San Rafael Pie De La Cuesta","12":"Nuevo Progreso","13":"El Tumbador","14":"El Rodeo","15":"Malacatán*","16":"Catarina","17":"Ayutla","18":"Ocós","19":"San Pablo","20":"El Quetzal","21":"La Reforma","22":"Pajapita","23":"Ixchiguán","24":"San José Ojetenam","25":"San Cristóbal Cucho","26":"Sipacapa","27":"Esquipulas Palo Gordo","28":"Río Blanco","29":"San Lorenzo","30":"La Blanca"},"13":{"0":"Nivel Departamental","1":"Huehuetenango","2":"Chiantla","3":"Malacatancito","4":"Cuilco","5":"Nentón","6":"San Pedro Necta","7":"Jacaltenango","8":"Soloma","9":"Ixtahuacán","10":"Santa Bárbara","11":"La Libertad","12":"La Democracia","13":"San Miguel Acatán","14":"San Rafael La Independencia","15":"Todos Santos Cuchumatán","16":"San Juan Atitán","17":"Santa Eulalia","18":"San Mateo Ixtatán","19":"Colotenango","20":"San Sebastián Huehuetenango","21":"Tectitán","22":"Concepción Huista","23":"San Juan Ixcoy","24":"San Antonio Huista","25":"San Sebastián Coatán","26":"Barillas","27":"Aguacatán","28":"San Rafael Petzal","29":"San Gaspar Ixchil","30":"Santiago Chimaltenango","31":"Santa Ana Huista","32":"Unión Cantinil"},"14":{"0":"Nivel Departamental","1":"Santa Cruz Del Quiché","2":"Chiché","3":"Chinique","4":"Zacualpa","5":"Chajul","6":"Chichicastenango","7":"Patzité","8":"San Antonio Ilotenango","9":"San Pedro Jocopilas","10":"Cunén","11":"San Juan Cotzal","12":"Joyabaj*","13":"Nebaj","14":"San Andrés Sajcabajá","15":"Uspantán","16":"Sacapulas","17":"San Bartolomé Jocotenango","18":"Canillá","19":"Chicamán","20":"Ixcán","21":"Pachalum"},"15":{"0":"Nivel Departamental","1":"Salamá","2":"San Miguel Chicaj","3":"Rabinal","4":"Cubulco",
        "5":"Granados","6":"El Chol","7":"San Jerónimo","8":"Purulhá"},"16":{"0":"Nivel Departamental","1":"Cobán","2":"Santa Cruz Verapaz","3":"San Cristóbal Verapaz","4":"Tactic","5":"Tamahú","6":"Tucurú","7":"Panzós","8":"Senahú","9":"San Pedro Carchá","10":"San Juan Chamelco","11":"Lanquín","12":"Cahabón","13":"Chisec","14":"Chahal","15":"Fray Bartolomé De Las Casas","16":"Santa Catalina La Tinta","17":"Raxruhá"},"17":{"0":"Nivel Departamental","1":"Flores","2":"San José","3":"San Benito","4":"San Andrés","5":"La Libertad","6":"San Francisco","7":"Santa Ana","8":"Dolores","9":"San Luis","10":"Sayaxché","11":"Melchor De Mencos","12":"Poptún","13":"Las Cruces","14":"El Chal"},"18":{"0":"Nivel Departamental","1":"Puerto Barrios","2":"Lívingston","3":"El Estor","4":"Morales","5":"Los Amates"},"19":{"0":"Nivel Departamental","1":"Zacapa","2":"Estanzuela","3":"Río Hondo","4":"Gualán","5":"Teculután","6":"Usumatlán","7":"Cabañas","8":"San Diego","9":"La Unión","10":"Huité","11":"San Jorge"},"20":{"0":"Nivel Departamental","1":"Chiquimula","2":"San José La Arada","3":"San Juan Ermita","4":"Jocotán","5":"Camotán","6":"Olopa","7":"Esquipulas","8":"Concepción Las Minas","9":"Quezaltepeque","10":"San Jacinto","11":"Ipala"},"21":{"0":"Nivel Departamental","1":"Jalapa","2":"San Pedro Pinula","3":"San Luis Jilotepeque","4":"San Manuel Chaparrón","5":"San Carlos Alzatate","6":"Monjas","7":"Mataquescuintla"},"22":{"0":"Nivel Departamental","1":"Jutiapa","2":"El Progreso","3":"Santa Catarina Mita*","4":"Agua Blanca","5":"Asunción Mita","6":"Yupiltepeque","7":"Atescatempa","8":"Jerez","9":"El Adelanto","10":"Zapotitlán","11":"Comapa","12":"Jalpatagua","13":"Conguaco*","14":"Moyuta","15":"Pasaco","16":"San José Acatempa","17":"Quesada"}}


def download_muni_data(api_url):
    import requests
    data = requests.post(api_url)
    return data.json()


def get_data_for_muni(dept, muni):
    api_url = 'http://resultados2015.tse.org.gt/2v/resultados-2015/data.php?departamento={}&municipio={}&te=1&titulo=heyheyhey'.format(dept, muni)
    print("Getting data for dept {} and muni {}".format(
        deps[dept], munis[str(dept)][muni]))
    return api_url


def download_data():
    for dept in deps:
        for muni in munis[str(dept)]:
            url = get_data_for_muni(dept, muni)
            print(download_muni_data(url)['resultados'])
            print('\n')


def main():
    download_data()


if __name__ == "__main__":
    main()
